services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: chat-app-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: mongodb_data