name: Deploy to Render
on:
  push:
    branches: [ master ]
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    environment:
      name: Production

    defaults:
      run:
        working-directory: ./client
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Optional: If you need to build your static site
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build site
        run: npm run build
      
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID_FRONTEND_PROD }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json"